/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./WrapprFactory.types";
import * as _1 from "./WrapprFactory.client";
import * as _2 from "./WrapprFactory.message-composer";
import * as _3 from "./WrapprMinter.types";
import * as _4 from "./WrapprMinter.client";
import * as _5 from "./WrapprMinter.message-composer";
import * as _6 from "./Wrappr721Base.types";
import * as _7 from "./Wrappr721Base.client";
import * as _8 from "./Wrappr721Base.message-composer";
export namespace contracts {
  export const WrapprFactory = { ..._0,
    ..._1,
    ..._2
  };
  export const WrapprMinter = { ..._3,
    ..._4,
    ..._5
  };
  export const Wrappr721Base = { ..._6,
    ..._7,
    ..._8
  };
}