/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./BaseFactory.types";
import * as _1 from "./BaseFactory.client";
import * as _2 from "./BaseFactory.message-composer";
import * as _3 from "./BaseMinter.types";
import * as _4 from "./BaseMinter.client";
import * as _5 from "./BaseMinter.message-composer";
import * as _6 from "./Wrappr721Base.types";
import * as _7 from "./Wrappr721Base.client";
import * as _8 from "./Wrappr721Base.message-composer";

  export const BaseFactory = { ..._0,
    ..._1,
    ..._2
  };
  export const BaseMinter = { ..._3,
    ..._4,
    ..._5
  };
  export const Wrappr721Base = { ..._6,
    ..._7,
    ..._8
  };