/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { ExecuteMsg, Timestamp, Uint64, Uint128, CreateMinterMsgForWrapprMinterInitMsgExtension, CollectionParams, CollectionInfo, WrapprMinterInitMsgExtension, Coin, InstantiateMsg, MinterParamsForNullable_Empty, Empty } from "./WrapprFactory.types";
export interface WrapprFactoryInterface {
  contractAddress: string;
  sender: string;
  createMinter: ({
    collectionParams,
    initMsg
  }: {
    collectionParams: CollectionParams;
    initMsg: WrapprMinterInitMsgExtension;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class WrapprFactoryClient implements WrapprFactoryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createMinter = this.createMinter.bind(this);
  }

  createMinter = async ({
    collectionParams,
    initMsg
  }: {
    collectionParams: CollectionParams;
    initMsg: WrapprMinterInitMsgExtension;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_minter: {
        collection_params: collectionParams,
        init_msg: initMsg
      }
    }, fee, memo, funds);
  };
}